services:
  # See: https://github.com/navikt/mock-oauth2-server#standalone-server
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.4.7
    ports:
      - 8080:8080
    hostname: localhost
    volumes:
      - ./conf:/app/conf
    environment:
      - JSON_CONFIG_PATH=/app/conf/config.json
